/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSendAnnouncementRouteImport } from './routes/_authenticated/send-announcement'
import { Route as AuthenticatedExportManagementRouteImport } from './routes/_authenticated/export-management'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedSystemRoleManageRouteImport } from './routes/_authenticated/system/role-manage'
import { Route as AuthenticatedSystemAccountManageRouteImport } from './routes/_authenticated/system/account-manage'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedOrdersReceiveSummaryListsRouteImport } from './routes/_authenticated/orders/receive-summary-lists'
import { Route as AuthenticatedOrdersReceiveListsRouteImport } from './routes/_authenticated/orders/receive-lists'
import { Route as AuthenticatedOrdersPaymentSummaryListsRouteImport } from './routes/_authenticated/orders/payment-summary-lists'
import { Route as AuthenticatedOrdersPaymentListsRouteImport } from './routes/_authenticated/orders/payment-lists'
import { Route as AuthenticatedOrdersCollectionSuccessRateRouteImport } from './routes/_authenticated/orders/collection-success-rate'
import { Route as AuthenticatedMerchantInfoListsRouteImport } from './routes/_authenticated/merchant/info-lists'
import { Route as AuthenticatedLogsRiskControlRouteImport } from './routes/_authenticated/logs/risk-control'
import { Route as AuthenticatedLogsMessageRecordRouteImport } from './routes/_authenticated/logs/message-record'
import { Route as AuthenticatedLogsMerchantRequestRouteImport } from './routes/_authenticated/logs/merchant-request'
import { Route as AuthenticatedFundSettlementListsRouteImport } from './routes/_authenticated/fund/settlement-lists'
import { Route as AuthenticatedFundRechargeWithdrawRouteImport } from './routes/_authenticated/fund/recharge-withdraw'
import { Route as AuthenticatedFundMerchantDailySummaryRouteImport } from './routes/_authenticated/fund/merchant-daily-summary'
import { Route as AuthenticatedFundCountryDailySummaryRouteImport } from './routes/_authenticated/fund/country-daily-summary'
import { Route as AuthenticatedFundAccountSettlementRouteImport } from './routes/_authenticated/fund/account-settlement'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedConfigRiskControlRuleRouteImport } from './routes/_authenticated/config/risk-control-rule'
import { Route as AuthenticatedConfigPaymentChannelRouteImport } from './routes/_authenticated/config/payment-channel'
import { Route as AuthenticatedBusinessMonthlySummaryRouteImport } from './routes/_authenticated/business/monthly-summary'
import { Route as AuthenticatedBusinessMerchantBindRouteImport } from './routes/_authenticated/business/merchant-bind'
import { Route as AuthenticatedBusinessDailySummaryRouteImport } from './routes/_authenticated/business/daily-summary'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSendAnnouncementRoute =
  AuthenticatedSendAnnouncementRouteImport.update({
    id: '/send-announcement',
    path: '/send-announcement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExportManagementRoute =
  AuthenticatedExportManagementRouteImport.update({
    id: '/export-management',
    path: '/export-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemRoleManageRoute =
  AuthenticatedSystemRoleManageRouteImport.update({
    id: '/system/role-manage',
    path: '/system/role-manage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemAccountManageRoute =
  AuthenticatedSystemAccountManageRouteImport.update({
    id: '/system/account-manage',
    path: '/system/account-manage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedOrdersReceiveSummaryListsRoute =
  AuthenticatedOrdersReceiveSummaryListsRouteImport.update({
    id: '/orders/receive-summary-lists',
    path: '/orders/receive-summary-lists',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersReceiveListsRoute =
  AuthenticatedOrdersReceiveListsRouteImport.update({
    id: '/orders/receive-lists',
    path: '/orders/receive-lists',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersPaymentSummaryListsRoute =
  AuthenticatedOrdersPaymentSummaryListsRouteImport.update({
    id: '/orders/payment-summary-lists',
    path: '/orders/payment-summary-lists',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersPaymentListsRoute =
  AuthenticatedOrdersPaymentListsRouteImport.update({
    id: '/orders/payment-lists',
    path: '/orders/payment-lists',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersCollectionSuccessRateRoute =
  AuthenticatedOrdersCollectionSuccessRateRouteImport.update({
    id: '/orders/collection-success-rate',
    path: '/orders/collection-success-rate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMerchantInfoListsRoute =
  AuthenticatedMerchantInfoListsRouteImport.update({
    id: '/merchant/info-lists',
    path: '/merchant/info-lists',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogsRiskControlRoute =
  AuthenticatedLogsRiskControlRouteImport.update({
    id: '/logs/risk-control',
    path: '/logs/risk-control',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogsMessageRecordRoute =
  AuthenticatedLogsMessageRecordRouteImport.update({
    id: '/logs/message-record',
    path: '/logs/message-record',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogsMerchantRequestRoute =
  AuthenticatedLogsMerchantRequestRouteImport.update({
    id: '/logs/merchant-request',
    path: '/logs/merchant-request',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFundSettlementListsRoute =
  AuthenticatedFundSettlementListsRouteImport.update({
    id: '/fund/settlement-lists',
    path: '/fund/settlement-lists',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFundRechargeWithdrawRoute =
  AuthenticatedFundRechargeWithdrawRouteImport.update({
    id: '/fund/recharge-withdraw',
    path: '/fund/recharge-withdraw',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFundMerchantDailySummaryRoute =
  AuthenticatedFundMerchantDailySummaryRouteImport.update({
    id: '/fund/merchant-daily-summary',
    path: '/fund/merchant-daily-summary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFundCountryDailySummaryRoute =
  AuthenticatedFundCountryDailySummaryRouteImport.update({
    id: '/fund/country-daily-summary',
    path: '/fund/country-daily-summary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFundAccountSettlementRoute =
  AuthenticatedFundAccountSettlementRouteImport.update({
    id: '/fund/account-settlement',
    path: '/fund/account-settlement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigRiskControlRuleRoute =
  AuthenticatedConfigRiskControlRuleRouteImport.update({
    id: '/config/risk-control-rule',
    path: '/config/risk-control-rule',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigPaymentChannelRoute =
  AuthenticatedConfigPaymentChannelRouteImport.update({
    id: '/config/payment-channel',
    path: '/config/payment-channel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessMonthlySummaryRoute =
  AuthenticatedBusinessMonthlySummaryRouteImport.update({
    id: '/business/monthly-summary',
    path: '/business/monthly-summary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessMerchantBindRoute =
  AuthenticatedBusinessMerchantBindRouteImport.update({
    id: '/business/merchant-bind',
    path: '/business/merchant-bind',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessDailySummaryRoute =
  AuthenticatedBusinessDailySummaryRouteImport.update({
    id: '/business/daily-summary',
    path: '/business/daily-summary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/export-management': typeof AuthenticatedExportManagementRoute
  '/send-announcement': typeof AuthenticatedSendAnnouncementRoute
  '/': typeof AuthenticatedIndexRoute
  '/business/daily-summary': typeof AuthenticatedBusinessDailySummaryRoute
  '/business/merchant-bind': typeof AuthenticatedBusinessMerchantBindRoute
  '/business/monthly-summary': typeof AuthenticatedBusinessMonthlySummaryRoute
  '/config/payment-channel': typeof AuthenticatedConfigPaymentChannelRoute
  '/config/risk-control-rule': typeof AuthenticatedConfigRiskControlRuleRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/fund/account-settlement': typeof AuthenticatedFundAccountSettlementRoute
  '/fund/country-daily-summary': typeof AuthenticatedFundCountryDailySummaryRoute
  '/fund/merchant-daily-summary': typeof AuthenticatedFundMerchantDailySummaryRoute
  '/fund/recharge-withdraw': typeof AuthenticatedFundRechargeWithdrawRoute
  '/fund/settlement-lists': typeof AuthenticatedFundSettlementListsRoute
  '/logs/merchant-request': typeof AuthenticatedLogsMerchantRequestRoute
  '/logs/message-record': typeof AuthenticatedLogsMessageRecordRoute
  '/logs/risk-control': typeof AuthenticatedLogsRiskControlRoute
  '/merchant/info-lists': typeof AuthenticatedMerchantInfoListsRoute
  '/orders/collection-success-rate': typeof AuthenticatedOrdersCollectionSuccessRateRoute
  '/orders/payment-lists': typeof AuthenticatedOrdersPaymentListsRoute
  '/orders/payment-summary-lists': typeof AuthenticatedOrdersPaymentSummaryListsRoute
  '/orders/receive-lists': typeof AuthenticatedOrdersReceiveListsRoute
  '/orders/receive-summary-lists': typeof AuthenticatedOrdersReceiveSummaryListsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/system/account-manage': typeof AuthenticatedSystemAccountManageRoute
  '/system/role-manage': typeof AuthenticatedSystemRoleManageRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/export-management': typeof AuthenticatedExportManagementRoute
  '/send-announcement': typeof AuthenticatedSendAnnouncementRoute
  '/': typeof AuthenticatedIndexRoute
  '/business/daily-summary': typeof AuthenticatedBusinessDailySummaryRoute
  '/business/merchant-bind': typeof AuthenticatedBusinessMerchantBindRoute
  '/business/monthly-summary': typeof AuthenticatedBusinessMonthlySummaryRoute
  '/config/payment-channel': typeof AuthenticatedConfigPaymentChannelRoute
  '/config/risk-control-rule': typeof AuthenticatedConfigRiskControlRuleRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/fund/account-settlement': typeof AuthenticatedFundAccountSettlementRoute
  '/fund/country-daily-summary': typeof AuthenticatedFundCountryDailySummaryRoute
  '/fund/merchant-daily-summary': typeof AuthenticatedFundMerchantDailySummaryRoute
  '/fund/recharge-withdraw': typeof AuthenticatedFundRechargeWithdrawRoute
  '/fund/settlement-lists': typeof AuthenticatedFundSettlementListsRoute
  '/logs/merchant-request': typeof AuthenticatedLogsMerchantRequestRoute
  '/logs/message-record': typeof AuthenticatedLogsMessageRecordRoute
  '/logs/risk-control': typeof AuthenticatedLogsRiskControlRoute
  '/merchant/info-lists': typeof AuthenticatedMerchantInfoListsRoute
  '/orders/collection-success-rate': typeof AuthenticatedOrdersCollectionSuccessRateRoute
  '/orders/payment-lists': typeof AuthenticatedOrdersPaymentListsRoute
  '/orders/payment-summary-lists': typeof AuthenticatedOrdersPaymentSummaryListsRoute
  '/orders/receive-lists': typeof AuthenticatedOrdersReceiveListsRoute
  '/orders/receive-summary-lists': typeof AuthenticatedOrdersReceiveSummaryListsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/system/account-manage': typeof AuthenticatedSystemAccountManageRoute
  '/system/role-manage': typeof AuthenticatedSystemRoleManageRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/export-management': typeof AuthenticatedExportManagementRoute
  '/_authenticated/send-announcement': typeof AuthenticatedSendAnnouncementRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/business/daily-summary': typeof AuthenticatedBusinessDailySummaryRoute
  '/_authenticated/business/merchant-bind': typeof AuthenticatedBusinessMerchantBindRoute
  '/_authenticated/business/monthly-summary': typeof AuthenticatedBusinessMonthlySummaryRoute
  '/_authenticated/config/payment-channel': typeof AuthenticatedConfigPaymentChannelRoute
  '/_authenticated/config/risk-control-rule': typeof AuthenticatedConfigRiskControlRuleRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/fund/account-settlement': typeof AuthenticatedFundAccountSettlementRoute
  '/_authenticated/fund/country-daily-summary': typeof AuthenticatedFundCountryDailySummaryRoute
  '/_authenticated/fund/merchant-daily-summary': typeof AuthenticatedFundMerchantDailySummaryRoute
  '/_authenticated/fund/recharge-withdraw': typeof AuthenticatedFundRechargeWithdrawRoute
  '/_authenticated/fund/settlement-lists': typeof AuthenticatedFundSettlementListsRoute
  '/_authenticated/logs/merchant-request': typeof AuthenticatedLogsMerchantRequestRoute
  '/_authenticated/logs/message-record': typeof AuthenticatedLogsMessageRecordRoute
  '/_authenticated/logs/risk-control': typeof AuthenticatedLogsRiskControlRoute
  '/_authenticated/merchant/info-lists': typeof AuthenticatedMerchantInfoListsRoute
  '/_authenticated/orders/collection-success-rate': typeof AuthenticatedOrdersCollectionSuccessRateRoute
  '/_authenticated/orders/payment-lists': typeof AuthenticatedOrdersPaymentListsRoute
  '/_authenticated/orders/payment-summary-lists': typeof AuthenticatedOrdersPaymentSummaryListsRoute
  '/_authenticated/orders/receive-lists': typeof AuthenticatedOrdersReceiveListsRoute
  '/_authenticated/orders/receive-summary-lists': typeof AuthenticatedOrdersReceiveSummaryListsRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/system/account-manage': typeof AuthenticatedSystemAccountManageRoute
  '/_authenticated/system/role-manage': typeof AuthenticatedSystemRoleManageRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/export-management'
    | '/send-announcement'
    | '/'
    | '/business/daily-summary'
    | '/business/merchant-bind'
    | '/business/monthly-summary'
    | '/config/payment-channel'
    | '/config/risk-control-rule'
    | '/errors/$error'
    | '/fund/account-settlement'
    | '/fund/country-daily-summary'
    | '/fund/merchant-daily-summary'
    | '/fund/recharge-withdraw'
    | '/fund/settlement-lists'
    | '/logs/merchant-request'
    | '/logs/message-record'
    | '/logs/risk-control'
    | '/merchant/info-lists'
    | '/orders/collection-success-rate'
    | '/orders/payment-lists'
    | '/orders/payment-summary-lists'
    | '/orders/receive-lists'
    | '/orders/receive-summary-lists'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/system/account-manage'
    | '/system/role-manage'
    | '/help-center'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/export-management'
    | '/send-announcement'
    | '/'
    | '/business/daily-summary'
    | '/business/merchant-bind'
    | '/business/monthly-summary'
    | '/config/payment-channel'
    | '/config/risk-control-rule'
    | '/errors/$error'
    | '/fund/account-settlement'
    | '/fund/country-daily-summary'
    | '/fund/merchant-daily-summary'
    | '/fund/recharge-withdraw'
    | '/fund/settlement-lists'
    | '/logs/merchant-request'
    | '/logs/message-record'
    | '/logs/risk-control'
    | '/merchant/info-lists'
    | '/orders/collection-success-rate'
    | '/orders/payment-lists'
    | '/orders/payment-summary-lists'
    | '/orders/receive-lists'
    | '/orders/receive-summary-lists'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/system/account-manage'
    | '/system/role-manage'
    | '/help-center'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/export-management'
    | '/_authenticated/send-announcement'
    | '/_authenticated/'
    | '/_authenticated/business/daily-summary'
    | '/_authenticated/business/merchant-bind'
    | '/_authenticated/business/monthly-summary'
    | '/_authenticated/config/payment-channel'
    | '/_authenticated/config/risk-control-rule'
    | '/_authenticated/errors/$error'
    | '/_authenticated/fund/account-settlement'
    | '/_authenticated/fund/country-daily-summary'
    | '/_authenticated/fund/merchant-daily-summary'
    | '/_authenticated/fund/recharge-withdraw'
    | '/_authenticated/fund/settlement-lists'
    | '/_authenticated/logs/merchant-request'
    | '/_authenticated/logs/message-record'
    | '/_authenticated/logs/risk-control'
    | '/_authenticated/merchant/info-lists'
    | '/_authenticated/orders/collection-success-rate'
    | '/_authenticated/orders/payment-lists'
    | '/_authenticated/orders/payment-summary-lists'
    | '/_authenticated/orders/receive-lists'
    | '/_authenticated/orders/receive-summary-lists'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/system/account-manage'
    | '/_authenticated/system/role-manage'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/send-announcement': {
      id: '/_authenticated/send-announcement'
      path: '/send-announcement'
      fullPath: '/send-announcement'
      preLoaderRoute: typeof AuthenticatedSendAnnouncementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/export-management': {
      id: '/_authenticated/export-management'
      path: '/export-management'
      fullPath: '/export-management'
      preLoaderRoute: typeof AuthenticatedExportManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/role-manage': {
      id: '/_authenticated/system/role-manage'
      path: '/system/role-manage'
      fullPath: '/system/role-manage'
      preLoaderRoute: typeof AuthenticatedSystemRoleManageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/account-manage': {
      id: '/_authenticated/system/account-manage'
      path: '/system/account-manage'
      fullPath: '/system/account-manage'
      preLoaderRoute: typeof AuthenticatedSystemAccountManageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/orders/receive-summary-lists': {
      id: '/_authenticated/orders/receive-summary-lists'
      path: '/orders/receive-summary-lists'
      fullPath: '/orders/receive-summary-lists'
      preLoaderRoute: typeof AuthenticatedOrdersReceiveSummaryListsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/receive-lists': {
      id: '/_authenticated/orders/receive-lists'
      path: '/orders/receive-lists'
      fullPath: '/orders/receive-lists'
      preLoaderRoute: typeof AuthenticatedOrdersReceiveListsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/payment-summary-lists': {
      id: '/_authenticated/orders/payment-summary-lists'
      path: '/orders/payment-summary-lists'
      fullPath: '/orders/payment-summary-lists'
      preLoaderRoute: typeof AuthenticatedOrdersPaymentSummaryListsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/payment-lists': {
      id: '/_authenticated/orders/payment-lists'
      path: '/orders/payment-lists'
      fullPath: '/orders/payment-lists'
      preLoaderRoute: typeof AuthenticatedOrdersPaymentListsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/collection-success-rate': {
      id: '/_authenticated/orders/collection-success-rate'
      path: '/orders/collection-success-rate'
      fullPath: '/orders/collection-success-rate'
      preLoaderRoute: typeof AuthenticatedOrdersCollectionSuccessRateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/merchant/info-lists': {
      id: '/_authenticated/merchant/info-lists'
      path: '/merchant/info-lists'
      fullPath: '/merchant/info-lists'
      preLoaderRoute: typeof AuthenticatedMerchantInfoListsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs/risk-control': {
      id: '/_authenticated/logs/risk-control'
      path: '/logs/risk-control'
      fullPath: '/logs/risk-control'
      preLoaderRoute: typeof AuthenticatedLogsRiskControlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs/message-record': {
      id: '/_authenticated/logs/message-record'
      path: '/logs/message-record'
      fullPath: '/logs/message-record'
      preLoaderRoute: typeof AuthenticatedLogsMessageRecordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs/merchant-request': {
      id: '/_authenticated/logs/merchant-request'
      path: '/logs/merchant-request'
      fullPath: '/logs/merchant-request'
      preLoaderRoute: typeof AuthenticatedLogsMerchantRequestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund/settlement-lists': {
      id: '/_authenticated/fund/settlement-lists'
      path: '/fund/settlement-lists'
      fullPath: '/fund/settlement-lists'
      preLoaderRoute: typeof AuthenticatedFundSettlementListsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund/recharge-withdraw': {
      id: '/_authenticated/fund/recharge-withdraw'
      path: '/fund/recharge-withdraw'
      fullPath: '/fund/recharge-withdraw'
      preLoaderRoute: typeof AuthenticatedFundRechargeWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund/merchant-daily-summary': {
      id: '/_authenticated/fund/merchant-daily-summary'
      path: '/fund/merchant-daily-summary'
      fullPath: '/fund/merchant-daily-summary'
      preLoaderRoute: typeof AuthenticatedFundMerchantDailySummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund/country-daily-summary': {
      id: '/_authenticated/fund/country-daily-summary'
      path: '/fund/country-daily-summary'
      fullPath: '/fund/country-daily-summary'
      preLoaderRoute: typeof AuthenticatedFundCountryDailySummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund/account-settlement': {
      id: '/_authenticated/fund/account-settlement'
      path: '/fund/account-settlement'
      fullPath: '/fund/account-settlement'
      preLoaderRoute: typeof AuthenticatedFundAccountSettlementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/risk-control-rule': {
      id: '/_authenticated/config/risk-control-rule'
      path: '/config/risk-control-rule'
      fullPath: '/config/risk-control-rule'
      preLoaderRoute: typeof AuthenticatedConfigRiskControlRuleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/payment-channel': {
      id: '/_authenticated/config/payment-channel'
      path: '/config/payment-channel'
      fullPath: '/config/payment-channel'
      preLoaderRoute: typeof AuthenticatedConfigPaymentChannelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/monthly-summary': {
      id: '/_authenticated/business/monthly-summary'
      path: '/business/monthly-summary'
      fullPath: '/business/monthly-summary'
      preLoaderRoute: typeof AuthenticatedBusinessMonthlySummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/merchant-bind': {
      id: '/_authenticated/business/merchant-bind'
      path: '/business/merchant-bind'
      fullPath: '/business/merchant-bind'
      preLoaderRoute: typeof AuthenticatedBusinessMerchantBindRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/daily-summary': {
      id: '/_authenticated/business/daily-summary'
      path: '/business/daily-summary'
      fullPath: '/business/daily-summary'
      preLoaderRoute: typeof AuthenticatedBusinessDailySummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedExportManagementRoute: typeof AuthenticatedExportManagementRoute
  AuthenticatedSendAnnouncementRoute: typeof AuthenticatedSendAnnouncementRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBusinessDailySummaryRoute: typeof AuthenticatedBusinessDailySummaryRoute
  AuthenticatedBusinessMerchantBindRoute: typeof AuthenticatedBusinessMerchantBindRoute
  AuthenticatedBusinessMonthlySummaryRoute: typeof AuthenticatedBusinessMonthlySummaryRoute
  AuthenticatedConfigPaymentChannelRoute: typeof AuthenticatedConfigPaymentChannelRoute
  AuthenticatedConfigRiskControlRuleRoute: typeof AuthenticatedConfigRiskControlRuleRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedFundAccountSettlementRoute: typeof AuthenticatedFundAccountSettlementRoute
  AuthenticatedFundCountryDailySummaryRoute: typeof AuthenticatedFundCountryDailySummaryRoute
  AuthenticatedFundMerchantDailySummaryRoute: typeof AuthenticatedFundMerchantDailySummaryRoute
  AuthenticatedFundRechargeWithdrawRoute: typeof AuthenticatedFundRechargeWithdrawRoute
  AuthenticatedFundSettlementListsRoute: typeof AuthenticatedFundSettlementListsRoute
  AuthenticatedLogsMerchantRequestRoute: typeof AuthenticatedLogsMerchantRequestRoute
  AuthenticatedLogsMessageRecordRoute: typeof AuthenticatedLogsMessageRecordRoute
  AuthenticatedLogsRiskControlRoute: typeof AuthenticatedLogsRiskControlRoute
  AuthenticatedMerchantInfoListsRoute: typeof AuthenticatedMerchantInfoListsRoute
  AuthenticatedOrdersCollectionSuccessRateRoute: typeof AuthenticatedOrdersCollectionSuccessRateRoute
  AuthenticatedOrdersPaymentListsRoute: typeof AuthenticatedOrdersPaymentListsRoute
  AuthenticatedOrdersPaymentSummaryListsRoute: typeof AuthenticatedOrdersPaymentSummaryListsRoute
  AuthenticatedOrdersReceiveListsRoute: typeof AuthenticatedOrdersReceiveListsRoute
  AuthenticatedOrdersReceiveSummaryListsRoute: typeof AuthenticatedOrdersReceiveSummaryListsRoute
  AuthenticatedSystemAccountManageRoute: typeof AuthenticatedSystemAccountManageRoute
  AuthenticatedSystemRoleManageRoute: typeof AuthenticatedSystemRoleManageRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedExportManagementRoute: AuthenticatedExportManagementRoute,
  AuthenticatedSendAnnouncementRoute: AuthenticatedSendAnnouncementRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBusinessDailySummaryRoute:
    AuthenticatedBusinessDailySummaryRoute,
  AuthenticatedBusinessMerchantBindRoute:
    AuthenticatedBusinessMerchantBindRoute,
  AuthenticatedBusinessMonthlySummaryRoute:
    AuthenticatedBusinessMonthlySummaryRoute,
  AuthenticatedConfigPaymentChannelRoute:
    AuthenticatedConfigPaymentChannelRoute,
  AuthenticatedConfigRiskControlRuleRoute:
    AuthenticatedConfigRiskControlRuleRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedFundAccountSettlementRoute:
    AuthenticatedFundAccountSettlementRoute,
  AuthenticatedFundCountryDailySummaryRoute:
    AuthenticatedFundCountryDailySummaryRoute,
  AuthenticatedFundMerchantDailySummaryRoute:
    AuthenticatedFundMerchantDailySummaryRoute,
  AuthenticatedFundRechargeWithdrawRoute:
    AuthenticatedFundRechargeWithdrawRoute,
  AuthenticatedFundSettlementListsRoute: AuthenticatedFundSettlementListsRoute,
  AuthenticatedLogsMerchantRequestRoute: AuthenticatedLogsMerchantRequestRoute,
  AuthenticatedLogsMessageRecordRoute: AuthenticatedLogsMessageRecordRoute,
  AuthenticatedLogsRiskControlRoute: AuthenticatedLogsRiskControlRoute,
  AuthenticatedMerchantInfoListsRoute: AuthenticatedMerchantInfoListsRoute,
  AuthenticatedOrdersCollectionSuccessRateRoute:
    AuthenticatedOrdersCollectionSuccessRateRoute,
  AuthenticatedOrdersPaymentListsRoute: AuthenticatedOrdersPaymentListsRoute,
  AuthenticatedOrdersPaymentSummaryListsRoute:
    AuthenticatedOrdersPaymentSummaryListsRoute,
  AuthenticatedOrdersReceiveListsRoute: AuthenticatedOrdersReceiveListsRoute,
  AuthenticatedOrdersReceiveSummaryListsRoute:
    AuthenticatedOrdersReceiveSummaryListsRoute,
  AuthenticatedSystemAccountManageRoute: AuthenticatedSystemAccountManageRoute,
  AuthenticatedSystemRoleManageRoute: AuthenticatedSystemRoleManageRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
